server:
  port: 8080
spring:
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/nfsyncdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false